CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'customer',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    category_id INTEGER NOT NULL,
    pack VARCHAR(100) DEFAULT '',
    mrp DECIMAL(10,2) DEFAULT 0,
    discount DECIMAL(10,2) DEFAULT 0,
    final_rate DECIMAL(10,2) DEFAULT 0,
    stock INTEGER DEFAULT 0,
    icon VARCHAR(20) DEFAULT '🎆',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_products_category
    FOREIGN KEY (category_id)
    REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_number VARCHAR(50) NOT NULL UNIQUE,

    customer_name VARCHAR(150) NOT NULL,

    phone VARCHAR(30) DEFAULT '',

    city VARCHAR(100) DEFAULT '',

    address TEXT,

    message TEXT,

    total DECIMAL(12,2) NOT NULL DEFAULT 0,

    status VARCHAR(30) NOT NULL DEFAULT 'NEW',

    source VARCHAR(30) NOT NULL DEFAULT 'WHATSAPP',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_orders_status
ON orders(status);

CREATE INDEX IF NOT EXISTS idx_orders_created
ON orders(created_at);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id BIGINT NOT NULL,

    product_id INTEGER NULL,

    product_code VARCHAR(50) DEFAULT '',

    product_name VARCHAR(200) NOT NULL,

    qty INTEGER NOT NULL,

    unit_price DECIMAL(10,2) NOT NULL,

    subtotal DECIMAL(12,2)
        GENERATED ALWAYS AS (qty * unit_price) STORED,

    CONSTRAINT fk_order_items_order
    FOREIGN KEY (order_id)
    REFERENCES orders(id)
    ON DELETE CASCADE,

    CONSTRAINT fk_order_items_product
    FOREIGN KEY (product_id)
    REFERENCES products(id)
    ON DELETE SET NULL
);

INSERT INTO categories (id, name)
VALUES
(1, 'Sparklers'),
(2, 'Flower Pots'),
(3, 'Rockets'),
(4, 'Bombs'),
(5, 'Chakkars'),
(6, 'Fancy Crackers'),
(7, 'Others')
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name;